[package]
name = "game"
version = "0.2.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
macroquad = "*"
serde_json = "1.0.108"
textwrap = "0.16.0"

[profile.dev.package."*"]
opt-level = 3
