name = "Village"

walls = [
 [1,1,5,5,3],
 [2,1,2,2,4]
]

# first bound is always at 0,0 this value is hardcoded
# also you can't have a negative point on the map
# for example this bound = [-1, 0] is invalid

bound = [10,10]

[interactables]
gate_west.position = [10,3,1,2]
gate_west.move_player = "route-1 3 5"

gate_north.position = [7,5,2,2]
gate_north.move_player = "move player idk"
